// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    I18n: typeof import('./src/components/dev/I18n.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    NavTab: typeof import('./src/components/NavTab.vue')['default']
    NoVnc: typeof import('./src/components/noVnc/noVnc.vue')['default']
    RouterView: typeof import('./src/components/RouterView.vue')['default']
    Store: typeof import('./src/components/store.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
