// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavTab: typeof import('./src/components/NavTab.vue')['default']
    RouterView: typeof import('./src/components/RouterView.vue')['default']
    Store: typeof import('./src/components/store.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
